apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-example-deployment
  labels:
    app: strapi-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi-example
  template:
    metadata:
      labels:
        app: strapi-example
    spec:
      containers:
      - name: strapiexample
        image: gcr.io/wise-logic-401107/strapi-example:latest
        env:
          - name: DATABASE_CLIENT
            value: ${DATABASE_CLIENT}
          - name: DATABASE_NAME
            value: ${DATABASE_NAME}
          - name: DATABASE_HOST
            value: ${DATABASE_HOST}
          - name: DATABASE_PORT
            value: ${DATABASE_PORT}
          - name: DATABASE_USERNAME
            value: ${DATABASE_USERNAME}
          - name: DATABASE_PASSWORD
            value: ${DATABASE_PASSWORD}
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: "0"
          - name: GOOGLE_API_KEY
            value: ${GOOGLE_API_KEY}
        ports:
        - containerPort: 1337

---
apiVersion: v1
kind: Service
metadata:
  name: strapi-service  # Der Name des Service
spec:
  selector:
    app: strapi-example  # Der Name des Deployments
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
  type: LoadBalancer  # Service-Typ